const flags = {
  AC: require('../assets/AC.jpg'),
  AL: require('../assets/AL.jpg'),
  AP: require('../assets/AP.jpg'),
  AM: require('../assets/AM.jpg'),
  BA: require('../assets/BA.jpg'),
  CE: require('../assets/CE.jpg'),
  DF: require('../assets/DF.jpg'),
  ES: require('../assets/ES.jpg'),
  GO: require('../assets/GO.jpg'),
  MA: require('../assets/MA.jpg'),
  MT: require('../assets/MT.jpg'),
  MS: require('../assets/MS.jpg'),
  MG: require('../assets/MG.jpg'),
  PA: require('../assets/PA.jpg'),
  PB: require('../assets/PB.jpg'),
  PR: require('../assets/PR.jpg'),
  PE: require('../assets/PE.jpg'),
  PI: require('../assets/PI.jpg'),
  RJ: require('../assets/RJ.jpg'),
  RN: require('../assets/RN.jpg'),
  RS: require('../assets/RS.jpg'),
  RO: require('../assets/RO.jpg'),
  RR: require('../assets/RR.jpg'),
  SC: require('../assets/SC.jpg'),
  SP: require('../assets/SP.jpg'),
  SE: require('../assets/SE.jpg'),
  TO: require('../assets/TO.jpg'),
};

export default flags;
